# Copyright 2024
{
    'name': 'Employee End Of Service Report',
    'version': '18.0.1.0.0',
    'summary': 'Generate End of Service report with benefits, leave balance, and loans.',
    'author': 'AutoGenerated',
    'website': 'https://example.com',
    'category': 'Human Resources',
    'depends': ['hr', 'hr_contract'],
    'data': [
        'views/hr_employee_view.xml',
        'report/hr_eos_report_templates.xml',
    ],
    'assets': {},
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
